### ISSUE TITLE
Tutorial по русский ?

### ISSUE THREAD

**Issue by PierreQuentel** [RAbraham/brython-blog#1]
Привет, Раджив !

Я видел ваш блогпост на Хабр о Бритоне. Merci beaucoup !

Я долго хочу, что перевод тюторяля по русский есть на сайте brython.info. Как видете, я плохо говорю русский язык... А вы можете делать перевод ?

**Comment by RAbraham** [comment]
Bonjour Pierre,
Est-ce que vous parlez anglais? Je ne parle pas la langue russe. Merci.

**Comment by PierreQuentel** [comment]
Bonjour Rajiv,

Sorry about that, I thought you were the author of this [blog post](https://habr.com/ru/company/piter/blog/532454/). My message asked if you could translate the Brython tutorial in Russian... I will try to contact the author of the translation.

Bonne journée,
Pierre

**Comment by RAbraham** [comment]
Interesting! I have more likes in Russian than my original English post :). Thanks for sharing! and great work with Brython!
